### ISSUE TITLE
Rename into facet

### ISSUE THREAD

**Issue by PowerKiKi** [Ecodev/natural#10]
Rename natural-search stuff into facet. Probably something like:

NaturalSearchConfiguration => NaturalSearchFacets
ItemConfiguration => Facet
BasicConfiguration => BasicFacet
DropdownConfiguration => DropdownFacet
FlagConfiguration => FlagFacet
ConfigurationSelectorComponent => FacetSelectorComponent

and all other related stuff...

**Comment by sambaptista** [comment]
Triste que t'ai renommé les configs en facet plutôt que les composants Dropdown. J'étais sur l'idée qu'on avait opté pour la deuxième option et qu'on avait forcé l'utilisation d'un composant exprès pour ça.

**Comment by PowerKiKi** [comment]
J'en suis le premier surpris ! :open_mouth: 

Je suis bien parti avec l'idée de renommer les dropdown. Mais pour être bien sûr de ce que je faisais, j'ai commencé par les commentaires que tu as laissé en TODO. Et là j'ai dû croiser des fils en cours de route parce que je suis convaincu que tes TODO m'indiquait que t'avais en fait changé d'avis. Et pourtant en relisant tes TODO aujourd'hui, je les comprends bien comme contraire à ce que j'ai fait. La suite naturelle du refactoring donne effectivement un résultat qui n'est pas ce qu'on avait dit...

Je comprends pas ce que j'ai foutu...

Ceci étant dit, je trouve que le résultat donne une API qui semble facile à comprendre et utiliser pour un utilisateur de la lib, comme [expliqué succinctement dans le commit](https://github.com/Ecodev/natural/commit/4590d51a34d438e37ac3043e6ff2e253132cf8fd). En particulier on évite la multiplication du terme "configuration" pour plein de chose différentes.

Cela me semble aussi bien coller au language [utilisé par Sylvain](https://support.ecodev.ch/issues/6431#change-23191):

> j'ai aussi ajouté des facettes pour pouvoir filtrer par date

Et aussi ce que [dit Mark](https://support.ecodev.ch/issues/6380), qui n'est pas particulièrement versé dans nos aspects techniques:

> Créer des facettes pour la recherche

Ou encore ce que tu [dit toi-même](https://support.ecodev.ch/issues/6205):

> Créer plein de facettes

Dans l'ensemble si c'est effectivement pas ce qu'on avait convenu, cela me semble quand même acceptable.
