### ISSUE TITLE
Error handler to FluentD

### ISSUE THREAD

**Issue by stissot** [Ecodev/natural#122]
Implement a error handler to catch client-side errors and forward them to FluentD via REST (http input)

The URL of the FluentD endpoint is app specific and can be retrieved from a client configuration or environment file depending what configuration method the app is using. This could be passed to the service using an injection token.

```ts
import {localConfig} from './shared/generated-config';

{provide: FLUENTD_URL, useValue: localConfig.fluentdUrl}
```
https://angular.io/api/core/ErrorHandler
https://docs.fluentd.org/input/http

**Comment by PowerKiKi** [comment]
Pour chopper des infos extra de l'app:

Dans Natural, qqch du genre:

```ts
interface LoggerExtra {
    getExtras(): Literal;
}
```


Dans notre app:

```ts
class MyLoggerExtra implements LoggerExtra {
    constructor(private readonly userService: UserService) {
    }

    public getExtras(): Literal {
        return {
            user: this.userService.getCurrent().id
        };
    }
}

{provide: LoggerExtra, use: MyLoggerExtra}
```

**Comment by PowerKiKi** [comment]
L'URL configurable doit être optionnel et en cas d'absence tout le truc devrait être totalement désactivé. Ceci permettant de pas logguer nos erreurs local de dev.

Conceptuellement c'est similaire à NaturalMatomoService, qui est désactivable, même si j'imagine un code assez différent, avec plutôt qqch comme ci-dessous. Cela me semble grandement simplifier l'utilisation:

```ts
@NgModule({
    // ...
})
export class NaturalLoggingModule {
    public static forRoot(config: {
        url: string | null;
        extraService?: Type<LoggerExtra>;
    }): ModuleWithProviders<NaturalLoggingModule> {
        const providers: Provider[] = [];

        if (config.url) {
            providers.push(
                {
                    provide: ErrorHandler,
                    use: NaturalErrorHandler,
                },
                {
                    provide: LOGGING_URL,
                    useValue: config.url,
                },
            );

            if (config.extraService) {
                providers.push({
                    provide: LoggerExtra,
                    use: config.extraService,
                });
            }
        }

        return {
            ngModule: NaturalLoggingModule,
            providers: providers,
        };
    }
}
```

Utilisation:


```ts
@NgModule({
    // ...
    imports: [
        NaturalLogginModule.forRoot({
            url: localConfig.loggingUrl,
            extraService: MyAppSpecificLogginExtraService,
        }),
    ],
    bootstrap: [AppComponent],
})
export class AppModule {
}
```

**Comment by stissot** [comment]
Afin de faciliter la réconciliation dans Elasticsearch des logs ingérés depuis le serveur Nginx (access+error) ou par l'application PHP et depuis le client web (principalement error) par Natural Logger, voici les propriétés JSON que recommande d'utiliser dans la requête POST envoyée à Fluent. La plupart des champs sont optionnels.

| Propriété | Exemple | Description |
|--------------|--------------|------------------|
| `host` | `ecodev.ch` | Le hostname du site courant (sans le scheme, ni port, ni path) |
| `user` | `stissot` | Si l'utilisateur est logué dans l'application, son username |
| `method` | `POST` | Méthode HTTP de la requête à l'origine de l'événement, si disponible |
| `path` | `/path/to/page` | La route de la page courante |
| `status` | `200` | Le code de statut HTTP de la requête à l'origine de l'événement |
| `referer` | `https://duckduckgo.com/` | Le  HTTP referer (`document.referer`) si disponible |
| `agent` | `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36` | La chaîne de user-agent complète (sera parsé côté Fluent) |
| `message` | `The user doesn't have a name property` | Le message d'erreur court (sans stacktrace) |
| `stacktrace` | `ReferenceError: unexistingFunction is not defined\n    at https://example.com/script.js` | stacktrace capturé comme string |
| `level` | `debug`, `info`, `log`,`warn`, `error` | Le niveau de criticité de l'événement

**Comment by PowerKiKi** [comment]
Closed via #187, #189 and #191
