### ISSUE TITLE
Possible to select a column that is not available

### ISSUE THREAD

**Issue by PowerKiKi** [Ecodev/natural#124]
This is closely related to https://github.com/Ecodev/natural/issues/123 and should be solved together.

It is possible to forge an URL with a column name that exist but is not available. The column will correctly not show the injected column, but the table will incorrectly show the column. Effectively giving access to user to things he was not supposed to see.

**Comment by sambaptista** [comment]
This is due to the direct transmission of the columns mentioned in the url to the table without any logic. When #123 will be fixed implementing `ColumnPicker` between `AbstractList` and `Table`, this issue should be fixed by itself.
