### ISSUE TITLE
AbstractList : persist columns selection

### ISSUE THREAD

**Issue by sambaptista** [Ecodev/natural#13]
Same behavior as natural-filter, pagination and sorting (session storage + url) to persist and recover columns selections.

**Comment by PowerKiKi** [comment]
Solved by https://github.com/Ecodev/natural/commit/37d84c3ede8e273a45f71024b65913f710f6bce0 and then https://github.com/Ecodev/natural/commit/6d974729e923a34ba1f05cfbf9ce8a92751370cd
