### ISSUE TITLE
Natural Relation - RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by daviserez** [Ecodev/natural#240]
When selecting an element in the dropdown of a Natural Relation component, we get a "RangeError: Maximum call stack size exceeded".

I suspect it comes from this [commit](https://github.com/Ecodev/natural/commit/f7f84297b744002c2929fec5defcc2f6096ee916), but I didn't make any further investigation.

It happens on our app (dilps/tiresias) but on the demo page too: 
![CleanShot 2023-05-11 at 17 27 53](https://github.com/Ecodev/natural/assets/832658/f1f3ba90-9e2d-4960-a023-9906e5070060)

It didn't constantly happen, removing an element from the list and adding a new one seems to trigger the error more often.

On dilps/tiresias, trying to add the card itself as linked card and emptying the text field seems to trigger the error too:
(this capture is from Firefox and the first one from Chrome, thus the error reported is not exactly the same)
![CleanShot 2023-05-11 at 17 42 33](https://github.com/Ecodev/natural/assets/832658/4aa37546-9b1b-4cfb-8ef9-128a47ea50d6)

Still, the component seems to work as intended (at least on dilps/tiresias), we just get spammed on our bug reporting app 🤕.

I get an "Error: ErrorService.watchAll error" error too when accessing the demo page of the relation component, but it's not related to our problem here.

**Comment by sambaptista** [comment]
C'est corrigé en ce qui me concerne, mais on va dire que c'est une proposition encore non publiée pour dilps car j'aimerais la validation d'Adrien qui s'était occupé de cette fonction en dernier. 

@PowerKiKi  : 

En cas d'appel à addRelations([null]), tu préremplissais le tableau avec of(null) ce qui donnait donc forkJoin([of(null])] dans le plus vide des cas. 

Donc le subscribe était exécuté quoiqu'il arrive alors que le but de filtrer les valeurs nulles était précisément de tout stopper si on envoi du vent, puisqu'il n'y a aucune relation à ajouter.

Si on n'ajoute aucune relation et que rien ne change, selectionChange ne doit pas non plus être appelé. 

Donc le test s'attendait à qqch de faux selon moi. C'est à dire qu'aucune mutation ne soit créée, mais qu'on s'attende quand même à émettre un changement. Hors je suis très persuadé que le selectionChange ne doit pas non plus être appelé. Le clear() sur le natural select n'a pas besoin d'être appelé non plus puisqu'il vient d'émettre un null et le clear() ne fait que re-setter à null.

Dis moi ce que t'en pense. 

En attendant je n'ai pas fixé le test. J'imagine que pour ce faire, il faut ajouter un 2e spy sur selectionChange afin de vérifier qu'il n'est pas appelé.

**Comment by sambaptista** [comment]
Voir [#236 ](https://github.com/Ecodev/natural/issues/236#issuecomment-1460530013)

**Comment by PowerKiKi** [comment]
@daviserez thanks for reporting. Fixed in https://github.com/unil-lettres/dilps-tiresias/commit/94c6039308b9751f6175f9c922c749cff1e3077c

The "Error: ErrorService.watchAll error" on demo page is normal because we simulate a service that unconditionally throw errors. If you are curious, see https://github.com/Ecodev/natural/blob/40ad31fe9f5086c7d258adcf9d1110d123a81b46/projects/natural/src/lib/testing/error.service.ts#L39-L53

@sambaptista I agree with what you said.
