### ISSUE TITLE
Cross icon in natural-select-hierarchic chip don't show anymore

### ISSUE THREAD

**Issue by daviserez** [Ecodev/natural#246]
Not much to add, see picture below (taken from the demo page). The button is still there and can still be clicked.
Perhaps a change in the icon's name?

![CleanShot 2023-11-24 at 14 23 46@2x](https://github.com/Ecodev/natural/assets/832658/2f59127d-3a20-4611-b198-f48140fd573d)

**Comment by PowerKiKi** [comment]
Meci du signalement, c'est corrigé dans Dilps via https://github.com/unil-lettres/dilps-tiresias/commit/874993c8d1fd1ec696f0a530369a8e77499f662a
