### ISSUE TITLE
Remove `NaturalAbstractModelService.mutate()`

### ISSUE THREAD

**Issue by PowerKiKi** [Ecodev/natural#28]
It seems this is unused in most (all?) our projects and does not seem to have much value. It should probably be removed entirely after triple-checking all our projects.

**Comment by sambaptista** [comment]
AbstraModelService standardizes CRUD operations, but in some cases, we need custom mutation with added value. 

It's the case for ichtus where BookingService terminates booking with specific mutation on specific api entry point. This do more than just update the object fields (like flag some other fields based on consolidated server side logic).

I guess it's a required function, unless you have some alternative to suggest ?
