### ISSUE TITLE
Use service as generic

### ISSUE THREAD

**Issue by PowerKiKi** [Ecodev/natural#29]
`NaturalAbstractList` and `NaturalAbstractDetail` generic types should be parameterized with a single implementation of `NaturalAbstractModelService`, instead of a multitude of Tall, Vall, Tone, Vone. The Tall/Vall things can be extracted from the service itself when needed.

This would allow to strongly type usage of the service itself in those classes and inheriting classes. Specifically prohibiting the usage of a service method if it is not supported, because not all services support fetching single items (or multiple items).

Usage before:

```ts
export class ActionComponent extends AbstractDetail<Action['action'],
    ActionVariables,
    CreateAction['createAction'],
    CreateActionVariables,
    UpdateAction['updateAction'],
    UpdateActionVariables,
    DeleteActions['deleteActions']> implements OnInit {
```

Usage after:

```ts
export class ActionComponent extends AbstractDetail<ActionService> implements OnInit {
```

**Comment by sambaptista** [comment]
LGTM
