### ISSUE TITLE
Adjust natural-inputs width to avoid ellipsis

### ISSUE THREAD

**Issue by sambaptista** [Ecodev/natural#30]
Adjust natural-input width to avoid ellipsis

![ellipsis](https://user-images.githubusercontent.com/5111137/73370335-5a9ce680-42b4-11ea-85c2-148edb408697.png)

**Comment by stissot** [comment]
On the other extreme, when the search module has a dropdown select with many active options and/or long labels, the input will not wrap the values neither use ellipsis and the clear button might become unaccessible depending of the viewport width. I think the input should have a maximum width and possibly truncate some labels: it's more important the clear button to be accessible.

![image](https://user-images.githubusercontent.com/869941/184328522-9f75632a-526f-44f1-bb7b-858b97bcc285.png)

**Comment by PowerKiKi** [comment]
Don't think this is still happening in MDC branch.

![image](https://user-images.githubusercontent.com/72603/224014613-3c53e967-e741-4a52-95f4-a4433c65b73c.png)
